# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ddf/ddf_extensions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x64\x66/ddf_extensions.proto\x1a google/protobuf/descriptor.proto:0\n\x05\x61lias\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\t:7\n\x0cstruct_align\x12\x1f.google.protobuf.MessageOptions\x18\xd3\x86\x03 \x01(\x08:1\n\x08resource\x12\x1d.google.protobuf.FieldOptions\x18\xb4\x87\x03 \x01(\x08:4\n\x0b\x66ield_align\x12\x1d.google.protobuf.FieldOptions\x18\xd4\x86\x03 \x01(\x08:8\n\x0b\x64isplayName\x12!.google.protobuf.EnumValueOptions\x18\x98\x88\x03 \x01(\t:5\n\rddf_namespace\x12\x1c.google.protobuf.FileOptions\x18\xd1\x86\x03 \x01(\t:4\n\x0c\x64\x64\x66_includes\x12\x1c.google.protobuf.FileOptions\x18\xd2\x86\x03 \x01(\tB!\n\x10\x63om.dynamo.protoB\rDdfExtensions')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ddf.ddf_extensions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.dynamo.protoB\rDdfExtensions'
# @@protoc_insertion_point(module_scope)
