# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource/liveupdate_ddf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v4.ddf import ddf_extensions_pb2 as ddf_dot_ddf__extensions__pb2
from v4.ddf import ddf_math_pb2 as ddf_dot_ddf__math__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dresource/liveupdate_ddf.proto\x12\x0f\x64mLiveUpdateDDF\x1a\x18\x64\x64\x66/ddf_extensions.proto\x1a\x12\x64\x64\x66/ddf_math.proto\"\x1a\n\nHashDigest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\"\xdf\x02\n\x0eManifestHeader\x12\x17\n\x0cmagic_number\x18\x01 \x02(\x05:\x01\x30\x12\x12\n\x07version\x18\x02 \x02(\x05:\x01\x30\x12L\n\x17resource_hash_algorithm\x18\x03 \x02(\x0e\x32\x1e.dmLiveUpdateDDF.HashAlgorithm:\x0bHASH_SHA256\x12M\n\x18signature_hash_algorithm\x18\x04 \x02(\x0e\x32\x1e.dmLiveUpdateDDF.HashAlgorithm:\x0bHASH_SHA256\x12J\n\x18signature_sign_algorithm\x18\x05 \x02(\x0e\x32\x1e.dmLiveUpdateDDF.SignAlgorithm:\x08SIGN_RSA\x12\x37\n\x12project_identifier\x18\x06 \x02(\x0b\x32\x1b.dmLiveUpdateDDF.HashDigest\"\x7f\n\rResourceEntry\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x10\n\x08url_hash\x18\x02 \x02(\x04\x12)\n\x04hash\x18\x03 \x02(\x0b\x32\x1b.dmLiveUpdateDDF.HashDigest\x12\x12\n\ndependants\x18\x04 \x03(\r\x12\x10\n\x05\x66lags\x18\x05 \x02(\r:\x01\x30\"\xa8\x01\n\x0cManifestData\x12/\n\x06header\x18\x01 \x02(\x0b\x32\x1f.dmLiveUpdateDDF.ManifestHeader\x12\x34\n\x0f\x65ngine_versions\x18\x02 \x03(\x0b\x32\x1b.dmLiveUpdateDDF.HashDigest\x12\x31\n\tresources\x18\x03 \x03(\x0b\x32\x1e.dmLiveUpdateDDF.ResourceEntry\"K\n\x0cManifestFile\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\x11\n\tsignature\x18\x02 \x02(\x0c\x12\x1a\n\x12\x61rchive_identifier\x18\x03 \x02(\x0c*`\n\rHashAlgorithm\x12\x10\n\x0cHASH_UNKNOWN\x10\x00\x12\x0c\n\x08HASH_MD5\x10\x01\x12\r\n\tHASH_SHA1\x10\x02\x12\x0f\n\x0bHASH_SHA256\x10\x03\x12\x0f\n\x0bHASH_SHA512\x10\x04*/\n\rSignAlgorithm\x12\x10\n\x0cSIGN_UNKNOWN\x10\x00\x12\x0c\n\x08SIGN_RSA\x10\x01*.\n\x11ResourceEntryFlag\x12\x0b\n\x07\x42UNDLED\x10\x01\x12\x0c\n\x08\x45XCLUDED\x10\x02\x42\'\n\x1b\x63om.dynamo.liveupdate.protoB\x08Manifest')

_HASHALGORITHM = DESCRIPTOR.enum_types_by_name['HashAlgorithm']
HashAlgorithm = enum_type_wrapper.EnumTypeWrapper(_HASHALGORITHM)
_SIGNALGORITHM = DESCRIPTOR.enum_types_by_name['SignAlgorithm']
SignAlgorithm = enum_type_wrapper.EnumTypeWrapper(_SIGNALGORITHM)
_RESOURCEENTRYFLAG = DESCRIPTOR.enum_types_by_name['ResourceEntryFlag']
ResourceEntryFlag = enum_type_wrapper.EnumTypeWrapper(_RESOURCEENTRYFLAG)
HASH_UNKNOWN = 0
HASH_MD5 = 1
HASH_SHA1 = 2
HASH_SHA256 = 3
HASH_SHA512 = 4
SIGN_UNKNOWN = 0
SIGN_RSA = 1
BUNDLED = 1
EXCLUDED = 2


_HASHDIGEST = DESCRIPTOR.message_types_by_name['HashDigest']
_MANIFESTHEADER = DESCRIPTOR.message_types_by_name['ManifestHeader']
_RESOURCEENTRY = DESCRIPTOR.message_types_by_name['ResourceEntry']
_MANIFESTDATA = DESCRIPTOR.message_types_by_name['ManifestData']
_MANIFESTFILE = DESCRIPTOR.message_types_by_name['ManifestFile']
HashDigest = _reflection.GeneratedProtocolMessageType('HashDigest', (_message.Message,), {
  'DESCRIPTOR' : _HASHDIGEST,
  '__module__' : 'resource.liveupdate_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLiveUpdateDDF.HashDigest)
  })
_sym_db.RegisterMessage(HashDigest)

ManifestHeader = _reflection.GeneratedProtocolMessageType('ManifestHeader', (_message.Message,), {
  'DESCRIPTOR' : _MANIFESTHEADER,
  '__module__' : 'resource.liveupdate_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLiveUpdateDDF.ManifestHeader)
  })
_sym_db.RegisterMessage(ManifestHeader)

ResourceEntry = _reflection.GeneratedProtocolMessageType('ResourceEntry', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEENTRY,
  '__module__' : 'resource.liveupdate_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLiveUpdateDDF.ResourceEntry)
  })
_sym_db.RegisterMessage(ResourceEntry)

ManifestData = _reflection.GeneratedProtocolMessageType('ManifestData', (_message.Message,), {
  'DESCRIPTOR' : _MANIFESTDATA,
  '__module__' : 'resource.liveupdate_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLiveUpdateDDF.ManifestData)
  })
_sym_db.RegisterMessage(ManifestData)

ManifestFile = _reflection.GeneratedProtocolMessageType('ManifestFile', (_message.Message,), {
  'DESCRIPTOR' : _MANIFESTFILE,
  '__module__' : 'resource.liveupdate_ddf_pb2'
  # @@protoc_insertion_point(class_scope:dmLiveUpdateDDF.ManifestFile)
  })
_sym_db.RegisterMessage(ManifestFile)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.dynamo.liveupdate.protoB\010Manifest'
  _HASHALGORITHM._serialized_start=855
  _HASHALGORITHM._serialized_end=951
  _SIGNALGORITHM._serialized_start=953
  _SIGNALGORITHM._serialized_end=1000
  _RESOURCEENTRYFLAG._serialized_start=1002
  _RESOURCEENTRYFLAG._serialized_end=1048
  _HASHDIGEST._serialized_start=96
  _HASHDIGEST._serialized_end=122
  _MANIFESTHEADER._serialized_start=125
  _MANIFESTHEADER._serialized_end=476
  _RESOURCEENTRY._serialized_start=478
  _RESOURCEENTRY._serialized_end=605
  _MANIFESTDATA._serialized_start=608
  _MANIFESTDATA._serialized_end=776
  _MANIFESTFILE._serialized_start=778
  _MANIFESTFILE._serialized_end=853
# @@protoc_insertion_point(module_scope)
